### DISCUSSION TITLE
Having problems with dual licensed packages.

### DISCUSSION THREAD

**Discussion by ghost** [actions/dependency-review-action#803] [Q&A]
```
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.3.4
        with:
          fail-on-severity: high
          allow-licenses: MIT, 0BSD, MIT AND Apache-2.0
```

With this setup , all my packages licenses seem invalid, How can i fix this:  
![image](https://github.com/user-attachments/assets/601fa573-3823-44f2-991c-55a28e40b601)
