### ISSUE TITLE
Deny license option not working?

### ISSUE THREAD

**Issue by markphip** [actions/dependency-review-action#115]
I am trying out the new version of this action, specifically the license checking. This is what my workflow looks like:

````yaml
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: high
          #
          # You can only include one of these two options: `allow-licenses` and `deny-licences`
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # allow-licenses: GPL-3.0, BSD-3-Clause, MIT
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          deny-licenses: AGPL-3.0, GPL-2.0, GPL-3.0
````

So I am trying to block adding GPL dependencies.

I then make a PR where I add this Python dependency to my requirements.txt:

https://github.com/aspiers/git-deps

The PR seems to recognize the package and if you click it links to the above URL which says it is GPL 2.0 licensed.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/933108/173831600-8ec4ae93-2a3c-4438-bac7-5890c844b4f3.png">

The action succeeds though:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/933108/173831762-210a54cc-2881-4335-8335-5320c1b045db.png">

Am I doing anything wrong here?

I will note that the above workflow is configured in a reusable workflow that lives in a different organization/repository. This has worked for the vulnerability parts of the action when testing so I assume it is not an issue.
