### ISSUE TITLE
Question: Run with pull request

### ISSUE THREAD

**Issue by hfhbd** [actions/dependency-review-action#202]
Version `2.1.0` supports pull requests. I use the same workflow for building the master branch as well as creating a pull request.
Do I really have to configure the action like this?
```yml
- uses: actions/dependency-review-action@v2
   if: github.event_name == 'push'
- name: Dependency Review
   uses: actions/dependency-review-action@v2
   if: github.event_name == 'pull_request'
   with:
     base-ref: ${{ github.event.pull_request.base.ref }}
     head-ref: ${{ github.event.pull_request.head.ref }}
```
If so, this action has access to the github event, hasn't it? So it could set the base/head-ref by itself?

**Comment by hfhbd** [comment]
After trial and error, you only need this action during PR, dependabot checks your main branch after each push:
```yml
- name: Dependency Review
   uses: actions/dependency-review-action@v2
   if: github.event_name == 'pull_request'
```
