### ISSUE TITLE
Support `push` events

### ISSUE THREAD

**Issue by reedloden** [actions/dependency-review-action#252]
Right now, only the `pull_request` and `pull_request_target` workflow events are supported. It would be great to also support `push` to catch any commits that may not have gone through a PR.

I'm aware of the [base-ref/head-ref](https://github.com/actions/dependency-review-action#base-refhead-ref) support, but it would be nice if this was supported by default without any special configuration.

**Comment by febuiles** [comment]
@reedloden The reason for using the PR events is that we get the refs automatically from the PR itself. How can we fetch those values by default for other types of events?

**Comment by reedloden** [comment]
@febuiles Wouldn't it be possible (for the majority of cases, at least) for you to compare `github.sha` with `github.event.before`? If `github.event.before` is `0000000000000000000000000000000000000000`, then just treat it as initial commit and scan the full contents of the commit (versus the diff). Hopefully, I got those variables correct. The docs are not that great.

**Comment by febuiles** [comment]
@reedloden Can those be interpolated in the config to achieve the same result? I haven't tried yet, but I'm thinking of something like:

```yaml
name: 'Dependency Review'
on: push

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          # insert the event fields here
          base-ref: ${{ github.event.before }}
          head-ref: ${{ github.sha }}
```
