### ISSUE TITLE
Fail to detect a license

### ISSUE THREAD

**Issue by jackpie1206** [actions/dependency-review-action#281]
I was testing with deny-licenses option and found that it failed to detect a license from https://www.npmjs.com/package/spook.js. The workflow I added was:

```
name: Dependency Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']

jobs:
  CheckDependency:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Check dependencies for known security issues'
        uses: actions/dependency-review-action@v2
        with:
          deny-licenses: GPL-1.0, GPL-2.0, GPL-3.0, LGPL-2.0, LGPL-2.1, LGPL-3.0, AGPL-1.0, AGPL-2.0, AGPL-3.0
```

And my test PR made these changes:
package.json
```
"spook.js": "0.0.1"
```
package-lock.json
```
    "spook.js": {
      "version": "0.0.1",
      "resolved": "https://registry.npmjs.org/spook.js/-/spook.js-0.0.1.tgz",
      "integrity": "sha512-D1/7VxEuQ7xk6z/kAROe4SUbd9CzxY4zOwVGnGHerd/SgLIVU5f4esDzQUsOCeArn933BZfWMKydH7l7dPEp0g=="
    }
```
![image](https://user-images.githubusercontent.com/45664340/195193307-493df3a3-cede-420f-9a2e-b78ee0023042.png)

However, the action run for the PR didn't fail. Instead, it reported that it couldn't detect a license for spook.js.
```
  We could not detect a license for the following dependencies:
  
  Python/blu-ring-viewer/package-lock.json » spook.js@0.0.1
  Python/blu-ring-viewer/package.json » spook.js@0.0.1
```

If I manually grab the file from https://registry.npmjs.org/spook.js/-/spook.js-0.0.1.tgz I can see LICENSE.md in it which is GPL-3.0. I can also use GitHub License API to check its license and it is "gpl-3.0": https://api.github.com/repos/arthurakay/spook.js/license
```
{
  "name": "LICENSE.md",
  "path": "LICENSE.md",
  "sha": "e72bfddabc15be5718a7cc061ac10e47741d8219",
  "size": 35148,
  "url": "https://api.github.com/repos/arthurakay/spook.js/contents/LICENSE.md?ref=master",
  "html_url": "https://github.com/arthurakay/spook.js/blob/master/LICENSE.md",
  "git_url": "https://api.github.com/repos/arthurakay/spook.js/git/blobs/e72bfddabc15be5718a7cc061ac10e47741d8219",
  "download_url": "https://raw.githubusercontent.com/arthurakay/spook.js/master/LICENSE.md",
  "type": "file",
  "content": "...removed...",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/arthurakay/spook.js/contents/LICENSE.md?ref=master",
    "git": "https://api.github.com/repos/arthurakay/spook.js/git/blobs/e72bfddabc15be5718a7cc061ac10e47741d8219",
    "html": "https://github.com/arthurakay/spook.js/blob/master/LICENSE.md"
  },
  "license": {
    "key": "gpl-3.0",
    "name": "GNU General Public License v3.0",
    "spdx_id": "GPL-3.0",
    "url": "https://api.github.com/licenses/gpl-3.0",
    "node_id": "MDc6TGljZW5zZTk="
  }
}
```

Did I do something wrong?
