### ISSUE TITLE
Support disabling vulnerability or license check

### ISSUE THREAD

**Issue by ericcornelissen** [actions/dependency-review-action#308]
Suggestion to add support to disable either the vulnerability or license check. From the user perspective, something along the lines of:

```yaml
- name: Dependency Review
  uses: actions/dependency-review-action@v2
  with:
    dependency-check: false   # `true` to enable, `false` to disable
    license-check: true       # `true` to enable, `false` to disable
```

I believe this is useful when you already use a different tool to do one of these checks. For example, say I use [`npm audit`](https://docs.npmjs.com/cli/v8/commands/npm-audit) for vulnerability scanning and I need a tool for license checking. In this scenario, using this Action is possible but I don't really need the dependency check. Moreover, it would likely lead to duplicate alerts, which can get noisy. Hence, I would want to disable the vulnerability scanning. One can imagine the same could be true for the license check.

#184 looks related as it would allow you to make only one of the two checks required. I still believe completely disabling one of the two checks would be a preferable solution in order to reduce noise.
