### ISSUE TITLE
Error using external config file in other org repo

### ISSUE THREAD

**Issue by futuredesignUK** [actions/dependency-review-action#369]
Using an external config file from an internal repo in the same org gives back the error

![image](https://user-images.githubusercontent.com/19208973/210773094-984dd899-c162-480c-8636-b4072c79a358.png)

Is there something wrong in my config? Does it have to be in a `.github` folder?

I have allowed Actions access to the config repo.

```
- name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          # external config file
          config-file: name-of-org/name-of-repo/.github/dependency-review-config.yml@main
```

**dependency-review-config.yml**

```
# Possible values: "critical", "high", "moderate", "low" 
fail-on-severity: 'low'

# You can only can only include one of these two options: `allow-licenses` and `deny-licences`
# ([String]). Only allow these licenses (optional)
# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses 
allow-licenses:
  - 'GPL-3.0'
  - 'BSD-3-Clause'
  - 'MIT'
  
# ([String]). Block the pull request on these licenses (optional)
# Possible values: Any  `spdx_id` value(s) from https://docs.github.com/en/rest/licenses 
# deny-licenses: 
# - 'LGPL-2.0'
# - 'BSD-2-Clause'
```
