### ISSUE TITLE
Support merge_group trigger

### ISSUE THREAD

**Issue by tenjaa** [actions/dependency-review-action#456]
When using this action with the new merge queue feature, I get the following error:
```
Error: Both a base ref and head ref must be provided, either via the `base_ref`/`head_ref` config options, or by running a `pull_request`/`pull_request_target` workflow.
```

It would be awesome, if this action can support the `merge_group` trigger out of the box.

**Comment by febuiles** [comment]
@tenjaa thanks for opening an issue apologies it took almost a month to get to it.

After [reading the docs](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group) it looks like we'd need to modify a bit [how we fetch the base and head refs if the event is of type `merge_group`](https://github.com/actions/dependency-review-action/blob/7d25be7d688d1683f13d4e1f8081a34944d6eba2/src/git-refs.ts#L10-L19), we currently drop everything but `pull_request` and `push`).

**Comment by tenjaa** [comment]
I don't know where I got the workaround from but this in the end worked for me:
```
    - uses: actions/dependency-review-action@v2
      with:
        allow-licenses: MIT, Apache-2.0, ISC, BSD-2-Clause, 0BSD, NOASSERTION
        base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
        head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
```
