### ISSUE TITLE
Invalid SPDX License

### ISSUE THREAD

**Issue by kamimanzoor** [actions/dependency-review-action#559]
Hi,

We have recently added dependency review in our workflows. We are getting "Invalid SPDX License" issue for quite a lot of our dependencies. Even though it [states](https://github.com/actions/dependency-review-action/issues/263#issuecomment-1311890229) that the latest release (v3) is fully SPDX-compliant and has support for AND/OR expressions. I have manually parse a couple of licenses like **BSD-2-Clause AND BSD-3-Clause** via the underlying library [spdx-expression-parse](https://github.com/jslicense/spdx-expression-parse.js) and it seems to parse without any issues. Please find the screenshot below:
<img width="896" alt="image" src="https://github.com/actions/dependency-review-action/assets/16157737/32a85e3f-f462-4340-90b2-4b86ade2255f">
The workflow code snippet alongside config file is shown below: 

```
- name: 'Dependency Review with config file'
   uses: actions/dependency-review-action@v3
   with:
     config-file: ${{ inputs.config-file }}
```
Small snippet from config file:

```
fail_on_severity: 'critical'
comment_summary_in_pr: true
license_check: true
allow_licenses: 
  - Apache-1.0
  - Apache-1.1
  - Apache-2.0
  - BSL-1.0
  - BSD-1-Clause
  - BSD-2-Clause
  - BSD-2-Clause-Patent
  - BSD-3-Clause
```

Any prompt response would be greatly appreciated as currently dependency review is not adding any meaningful value for us.
