### ISSUE TITLE
"Invalid SPDX License" after upgrading JSTS package

### ISSUE THREAD

**Issue by mprins** [actions/dependency-review-action#575]
After upgrading the JSTS package from 2.10.0 to 2.11.0 we're getting the message that it has an "Invalid SPDX License" "(EDL-1.0 OR EPL-1.0)"  (the license information [has not changed in 7 years](https://github.com/bjornharrtell/jsts/commit/245a98cda273f0efb9910a12fd4080ef357cb308)

We're using the following configuration
```yaml
  dependency-review:
    name: 'Dependency Review'
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v3
        with:
          deny-licenses: GPL-2.0+, AGPL-3.0+
```

see https://github.com/B3Partners/tailormap-viewer/actions/runs/6323648494?pr=484 for the logs/output.

Do you have any hints or ideas?

possibly related to #559
