### ISSUE TITLE
Run `actions/dependency-review-action@v2` `Error: Forbidden`

### ISSUE THREAD

**Issue by jsoref** [actions/dependency-review-action#576]
https://github.com/check-spelling-sandbox/superset/actions/runs/6328881314/job/17188012430#step:3:8

```yaml
Current runner version: '2.309.0'
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
Download action repository 'actions/dependency-review-action@v2' (SHA:0efb1d1d84fc9633afcdaad14c485cbbc90ef46c)
```

```yaml
Dependency Review
Run actions/dependency-review-action@v2
  with:
    fail-on-severity: high
    deny-licenses: MS-LPL, BUSL-[1](https://github.com/check-spelling-sandbox/superset/actions/runs/6328881314/job/17188012430#step:3:1).1, QPL-1.0, Sleepycat, SSPL-1.0, CPOL-1.0[2](https://github.com/check-spelling-sandbox/superset/actions/runs/6328881314/job/17188012430#step:3:2), AGPL-[3](https://github.com/check-spelling-sandbox/superset/actions/runs/6328881314/job/17188012430#step:3:3).0, GPL-1.0+, BSD-[4](https://github.com/check-spelling-sandbox/superset/actions/runs/6328881314/job/17188012430#step:3:4)-Clause-UC, NPL-1.0, NPL-1.1, JSON
    repo-token: ***
    fail-on-scopes: runtime
Error: Forbidden
````

There are other tickets for this, but they're for older versions (v1): #75 #95.

Actions should have useful error messages for failure cases. `Forbidden` does not satisfy that requirement.

Note that the current readme still occasionally mentions `v2`:

https://github.com/actions/dependency-review-action/blame/64a6d1a0b806afa49305e6231822b4b8b966399a/README.md#L130-L131

The error reporting is apparently fixed in v3:
https://github.com/check-spelling-sandbox/superset/actions/runs/6328959782/job/17188258967

```
Error: Dependency review is not supported on this repository. Please ensure that Dependency graph is enabled along with GitHub Advanced Security on private repositories, see https://github.com/check-spelling-sandbox/superset/settings/security_analysis
```

But, as `v2` is still referenced in this readme, it's clearly still "quasi" supported.

Recommendations:
* Either upgrade the readme to stop mentioning `v2` (this seems like a good idea), or
* Back port the fix to improve the error reporting to the `v2` branch (this seems fairly harmless -- although I can't determine which piece is responsible for it at this time, as the most obvious commit https://github.com/actions/dependency-review-action/commit/e6aba92fb0bf7f19a97cacc92b420cd35b3809b6 changes a line that existed from the beginning)
