### ISSUE TITLE
Bug: Error "fetch failed" when fetching v3.1.1 

### ISSUE THREAD

**Issue by lindeberg** [actions/dependency-review-action#609]
We are getting error "fetch failed" when targeting the brand new patch v3.1.1:
![image](https://github.com/actions/dependency-review-action/assets/15940340/be489f76-a517-4cdc-96e8-f49519738122)

Targeting v3.1.0 works fine.

**Comment by febuiles** [comment]
@lindeberg thanks for the report, we recently updated our HTTP libraries and I was expecting something like this to show up! Can you share the YAML file you're using for the Action (please obscure any private info) so we can reproduce?

**Comment by lindeberg** [comment]
```
name: Dependency Review
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    name: Dependency review
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: low
          license-check: false
```
