### ISSUE TITLE
Python `purl` URLs seem incorrect, some examples don't work

### ISSUE THREAD

**Issue by unchris** [actions/dependency-review-action#627]
Across this repo, the examples for Python PURLs uses `pkg:pip` but the [purl-spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) says it should be `pkg:pypi`.

Here's a [code search](https://github.com/search?q=repo%3Aactions%2Fdependency-review-action%20pkg%3Apip&type=code) showing all the instances of this.

I've been trying to use this action in a new workflow to deny, for example, `pycrypto`, which is one of the examples in the `action.yml` among other places:

```yaml
      - uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          comment-summary-in-pr: "on-failure"
          deny-packages: "pkg:pip/pycrypto, pkg:pypi/pycrypto, pkg:PYPI/pycrypto, pkg:PIP/pycrypto, pycrypto"
```

I've tried a number of variants but none of them blocks pycrypto. After adding debug logging though, I found this is because the `pycrypto` purl is blank in the run:

```json
{"change_type":"added",
"manifest":"pyproject.toml",
"ecosystem":"pip",
"name":"pycrypto",
"version":"",
"package_url":"",
"license":null,
"source_repository_url":"https://github.com/pycrypto/pycrypto",
"scope":"runtime",
"vulnerabilities":[]},
```

here's one it gets right:

```json
{"change_type":"added",
"manifest":"pyproject.toml",
"ecosystem":"pip",
"name":"howso-engine",
"version":"10.0.0",
"package_url":"pkg:pypi/howso-engine@10.0.0",
"license":null,
"source_repository_url":"https://github.com/howsoai/howso-engine-py",
"scope":"runtime",
"vulnerabilities":[]},
```

even weirder is what it comes up with for `python` itself:

```json
{"change_type":"added",
"manifest":"pyproject.toml",
"ecosystem":"pip",
"name":"python",
"version":">= 3.8,< 3.12",
"package_url":"",
"license":null,
"source_repository_url":"https://github.com/mathspp/building-a-python-compiler-and-interpreter",
"scope":"runtime",
"vulnerabilities":[]},
```

This is in a `pyproject.toml`-based project using `poetry`. Here's the dependency section for completeness:

```toml
[tool.poetry.dependencies]
python = ">=3.8,<3.12"
cowsay = "~=5.0"
requests = "*"
opentelemetry-instrumentation = "0.39b0"
howso-engine = "10.0.0"
pycrypto = "*"
```

(the weird set of dependencies was chosen specifically to trigger warnings, this project exists to test Github advanced security and related tooling like this dependency review action 😂 )

**Comment by febuiles** [comment]
@unchris do you see `pycrypto` when you go to github.com/<user>/<repo>/network/dependencies if you merge the PR? If so, can you share a screenshot of the row? Looking at `pycrypto`'s project's `setup.cfg` the name is set dynamically, and I'm wondering Dependency Graph is not able to properly parse the package name.

**Comment by unchris** [comment]
I created and merged a smaller PR that only had the following dependencies:

```toml
[tool.poetry.dependencies]
python = ">=3.9,<3.12"
cowsay = "~=5.0"
pycrypto = "*"
```

This is what I see in the Dependency Graph for python deps:

<img width="908" alt="Screenshot 2023-12-01 at 10 22 28 AM" src="https://github.com/actions/dependency-review-action/assets/32913178/895aa100-1ef0-4f0e-a5db-306401d86c1d">

Here's the output from the PR:

```bash
Run actions/dependency-review-action@v3
  with:
    fail-on-severity: high
    comment-summary-in-pr: on-failure
    deny-packages: pkg:pypi/pycrypto
    deny-licenses: AGPL-3.0
    repo-token: ***
    retry-on-snapshot-warnings: false
    retry-on-snapshot-warnings-timeout: 120
Dependency review did not detect any denied packages
Vulnerabilities
  Dependency review did not detect any vulnerable packages with severity level "high" or higher.
Licenses
  
  We could not detect a license for the following dependencies:
  pyproject.toml » pycrypto@
Denied
  Config: pkg:pypi/pycrypto
Dependency Changes
  File: pyproject.toml
  + pycrypto@
```
