### ISSUE TITLE
Unknown License but license available via github API

### ISSUE THREAD

**Issue by riosje** [actions/dependency-review-action#704]
![image](https://github.com/actions/dependency-review-action/assets/55195249/19f8a01b-366c-437c-8436-1cde07506443)
---

Hello guys I'm facing issues using this action in one of my workflows because it always mark my action with unknown license despite to have the license properly configured everywhere.

**This is the action returning the issue**
https://github.com/nodesource/setup-nsolid

**This is a RUN with the issue**
https://github.com/nodesource/setup-nsolid/actions/runs/8065465089

**This is the Workflow I'm testing**
https://github.com/nodesource/setup-nsolid/blob/jeff/fixdepreview/.github/workflows/dependency-review.yaml

This is the license the Github API returns
`gh api /repos/nodesource/setup-nsolid/license | jq -r .license`
```json
{
  "key": "mit",
  "name": "MIT License",
  "spdx_id": "MIT",
  "url": "https://api.github.com/licenses/mit",
  "node_id": "MDc6TGljZW5zZTEz"
}
```

this is a pipeline to repro the issue
```yaml
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
```
