### ISSUE TITLE
[BUG] Error "fetch failed" when using proxy

### ISSUE THREAD

**Issue by lindeberg** [actions/dependency-review-action#814]
**Describe the bug**
Error "fetch failed" when using proxy on a self-hosted runner with a proxy with least privelege network access, and these domains are allowed:
- api.deps.dev
- api.securityscorecards.dev

```shell
2024-08-16T06:36:11.3271510Z Dependency review did not detect any denied packages
2024-08-16T06:36:31.3476555Z ##[error]fetch failed
```

**To Reproduce**
1. Set up a self-hosted runner with least privelege network access
```yaml
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          license-check: false
```

2. Allow the domains above
3. Run dependency-review such that it triggers calls to these domains
4. See the error

**Expected behavior**
It should be all good!

**Screenshots**
![image](https://github.com/user-attachments/assets/7038ae32-4129-4a74-8e21-954f36da7577)

**Action version**
v4.3.4
