### ISSUE TITLE
[BUG] Action fails when removing a dependency version specified in deny_packages

### ISSUE THREAD

**Issue by ellenfieldn** [actions/dependency-review-action#887]
**Describe the bug**
If a repository already has a dependency that is specified as part of `deny_packages`, the dependency review action will block any commit that attempts to remove that dependency.

**To Reproduce**
1. Create a dotnet project using FluentAssertions@8.0.1. Ensure that this change is merged into the default branch.
2. Introduce a GitHub Action workflow that will use the dependency review action and add `deny-packages: pkg:nuget/FluentAssertions@8.0.0, pkg:nuget/FluentAssertions@8.0.1`. 
3. Submit a Pull Request that changes the version of FluentAssertions that is being used to version 7.1.0 (a version that is not explicitly denied.)
4. The dependency review action will return an error status and will report that the version in the previous commit is a denied dependency.

**Expected behavior**
Dependency review action should not block a commit that **removes** a dependency that is not allowed.

**Screenshots**
<details><summary>Job Output and PR Comment</summary>
<p>

Screenshot showing the job failing along with relevant output
![Image](https://github.com/user-attachments/assets/5645aefb-ff72-41f1-b287-2e3aac9e221f)

Screenshot showing the PR comment that is generated as a result of the job
![Image](https://github.com/user-attachments/assets/fc861eea-a04b-4fe7-a2e6-a6d7d15251f0)

</p>
</details> 

**Action version**
v4.5.0 - `uses: actions/dependency-review-action@v4.5.0`

**Examples**
I don't have a public example, but here's a snippet with the workflow
<details><summary>Dependency Review Action</summary>
<p>

``` yaml
name: 'Copy of Workflow'
on: [pull_request]

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.5.0
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-3.0
          deny-packages: pkg:nuget/FluentAssertions@8.0.0, pkg:nuget/FluentAssertions@8.0.1
          fail-on-scopes: development, runtime
          comment-summary-in-pr: always
```
</p>
</details> 

If you have encountered a problem with a specific package (e.g. issue with license or attributions data) please share details about the package, as well as a link to the manifest where it's being referenced.

We blocked FluentAssertions 8.0.0 and 8.0.1, and see an error when we attempt to revert to 7.1.0. I can't provide the full `.csproj` file, but if this turns out to be difficult to reproduce, can help create a minimal repro.

**Additional context**
This behavior has me wondering:
- Is this unique to the deny_packages, or would we also see the same behavior with disallowing specific licenses?
  - edit: I didn't test this explicitly, but the code appears to filter out package removals before checking licenses. 
- Would this have occurred had the dependency been removed entirely? Or is it related to denying an explicit version?
  - Edit, this appears to impact: Denying a package outright, denying a specific version of a package, and denying an entire namespace.

I haven't looked into those questions at all, but will take a look if time permits. edit: took a look
