### ISSUE TITLE
[BUG] MIT License identified as invalid starting on version 4.3.4

### ISSUE THREAD

**Issue by mathiasquatorze** [actions/dependency-review-action#907]
**Describe the bug**
Starting on version v4.3.4, the MIT license began displaying the following error: 
```  
  The following dependencies have incompatible licenses:
  .github/workflows/dependabot-dependency-review.yml » actions/dependency-review-action@4.*.* – License: MIT
  Error: Dependency review detected incompatible licenses.
```
The action is configured as: 
```
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          config-file: './.github/linters/dependabot-config.yml'
```
And the config file: 
```
fail_on_severity: 'critical'
comment-summary-in-pr: false
allow-licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'Apache-2.0 AND BSD-3-Clause AND Python-2.0'
  - 'Apache-2.0 AND ISC'
  - 'Apache-2.0 OR (Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause)'
  - 'Apache-2.0 OR MPL-1.1 OR (Apache-2.0 AND MPL-1.1)'
  - 'Apache-2.0 OR MS-PL OR (Apache-2.0 AND MS-PL)'
  - 'Apache-2.0 OR Unlicense OR (Apache-2.0 AND Unlicense)'
  - 'BlueOak-1.0.0'
  - 'BSD-2-Clause'
  - 'BSD-2-Clause AND BSD-3-Clause'
  - 'BSD-2-Clause AND ISC'
  - 'BSD-2-Clause OR (MIT OR Apache-2.0)'
  - 'BSD-3-Clause'
  - 'BSD-3-Clause AND MIT'
  - 'BSD-3-Clause AND BSD-3-Clause-Clear'
  - 'CC-BY-4.0'
  - 'ISC'
  - 'ISC AND MIT'
  - 'MIT' # <--- MIT IS HERE
  - 'MIT-0'
  - 'MIT AND MPL-2.0'
  - 'MIT AND PSF-2.0'
  - 'MIT AND Python-2.0'
  - 'MIT AND Zlib'
  - 'MIT OR (CC0-1.0 AND MIT)'
  - 'MIT OR WTFPL'
  - 'MIT OR WTFPL OR (MIT AND WTFPL)'
  - 'MPL-2.0'
  - 'PSF-2.0'
  - 'Python-2.0'
  - 'Python-2.0 AND Python-2.0 AND BSD-3-Clause AND Python-2.0 AND BSD-3-Clause AND 0BSD' 
```
**To Reproduce**
1. Setup the action as described above using version v4.3.2
2. If it passes, update the version to v4.5.0
3. Workflow fails

**Expected behavior**
I expect the workflow to pass as it did on v4.3.2 of the workflow.

**Screenshots**
No applicable screenshots

**Action version**
What version of the action are you using in your workflows

_Note: if you're not running the [latest release](https://github.com/actions/dependency-review-action/releases/latest) please try that first!_

I was able to run v4.3.2 and v4.3.3 successfully, however any versions past that, including and up to v4.5.0 cause the issue.

**Examples**
Not public examples, since I am running on GitHub Enterprise Cloud (Could this be the issue?)

**Additional context**
This is currently running on GitHub Enterprise Cloud, on a hosted ubuntu-latest runner.

**Comment by jebeaudet** [comment]
This is easily reproducible here https://github.com/jebeaudet/dependency-review-bug/pull/1

It works (as shown here : https://github.com/jebeaudet/dependency-review-bug/pull/2) If the yaml file with the allowed license only contains : 
```
fail_on_severity: 'critical'
comment-summary-in-pr: false
allow-licenses:
  - 'MIT'
```

Possibly related? https://github.com/actions/dependency-review-action/pull/719

**Comment by martin-morin** [comment]
This issue is hindering my ability to utilise any new versions until it is resolved. MIT licenses are among the most widely used licenses available.

**Comment by martin-morin** [comment]
Thanks will test with the latest version

**Comment by martin-morin** [comment]
It did solve the issue thanks.

**Comment by dangoor** [comment]
Please see if v4.7.0 fixes the issue for you.

**Comment by baltie** [comment]
I'm still getting the error, unfortunately. From the logs:

```
The following dependencies have incompatible licenses:
  .github/workflows/dependency-review.yaml » actions/dependency-review-action@4.7.0 – License: MIT
```

This is our config file for one of our repositories:

```yaml
fail-on-severity: high
comment-summary-in-pr: always
license-check: true
allow-licenses:
  - Apache-2.0
  - BSD-3-Clause
  - MIT
  - PostgreSQL
  - MIT AND MIT AND BSD-3-Clause AND BSD-3-Clause
allow-dependencies-licenses:
  - pkg:nuget/Microsoft.OpenApi
  - pkg:nuget/Microsoft.Testing.Extensions.CodeCoverage
```

The two last ones are to get around issues with version 4.3.3
