### ISSUE TITLE
[BUG] NPM vulnerability not detected

### ISSUE THREAD

**Issue by cristianrgreco** [actions/dependency-review-action#936]
**Describe the bug**
When I run `npm audit` I see 0 vulnerabilities. I install a dependency which introduces 2 critical vulnerabilities and run `npm audit`, I see the 2 critical vulnerabilities. If I raise a PR with this change, this action detects no issues.

**To Reproduce**
1. Raise a PR introducing critical vulnerability, e.g. @google-cloud/datastore@10.0.1
2. Run this action.

**Expected behavior**
Expect the action to show the introduction of the vulnerability and potentially fail the pipeline.

**Action version**
v4

**Examples**
Here's the PR which introduced 2 critical vulnerabilities: https://github.com/testcontainers/testcontainers-node/pull/1024/commits/ad21c6270a8a22bac7b2dadf30b77ac54502aaf5

Here's the action run: https://github.com/testcontainers/testcontainers-node/actions/runs/15297291065/job/43029309641

You can see it correctly detected the change, but didn't detect the vulnerability.

**Additional context**

Here's the action definition, everything set to defaults:

```yaml
name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
```
