### ISSUE TITLE
Getting Error: Forbidden on Dependency Review

### ISSUE THREAD

**Issue by xrude** [actions/dependency-review-action#95]
I try to deploy my dependency-review action file but get Error: Forbidden
![image](https://user-images.githubusercontent.com/82888965/171158435-551e0865-71ba-4c66-9f11-16df0c5ad10e.png)

My dependency-review-action.yml

```
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
```
